version: '3'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile:  Dockerfile
        networks:
            - frontend
        ports:
            - "${PROXY_PORT}:80"
        volumes:
            - "${STATIC_FILE_VOLUME}:/srv/images"
    
networks:
    frontend: # Cannot proxy pass from one network to another via nginx
    backend:
